<?php

function node_block_theme_suggestions_block_alter(array &$suggestions, array $vars) {
  // Support for node block theme suggestions
  if (isset($vars['elements']['#configuration']['theme_suggestion'])) {
    $base_plugin_id = str_replace('-', '_', $vars['elements']['#base_plugin_id']);
    $theme_suggestion = $vars['elements']['#configuration']['theme_suggestion'];
    if (!empty($theme_suggestion)) {
      $theme_suggestion = preg_replace('@[^a-z0-9]+@', '_', strtolower($theme_suggestion));
      $suggestions[] = 'block__' . $base_plugin_id . '__' . $theme_suggestion;
    }
  }
}

/**
 * Implements hook_block_build_BASE_BLOCK_ID_alter().
 */
function node_block_block_build_node_block_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  // Skip BigPipe for this block.
  $build['#create_placeholder'] = FALSE;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_block_preprocess_block(&$vars) {
  $vars['node'] = \Drupal::request()->get('node');
}
